name: Test

on:
  push:
    branches:
      - 'main'
      - 'feature/**'
    paths:
      - 'lambdas/**'
      - 'tests/**'
      - 'tasks.py'
      - 'pyproject.toml'
      - '.github/workflows/test.yml'
  pull_request:
    branches:
      - '**'
    paths:
      - 'lambdas/**'
      - 'tests/**'
      - 'tasks.py'
      - 'pyproject.toml'
      - '.github/workflows/test.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
        fail-fast: false
        matrix:
            PYTHON_VERSION: ['3.9', '3.10', '3.11', '3.12']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install invoke
          pip install .

      - name: Run tests
        run: inv test
